default:
  just -l

websocat:
  rlwrap websocat ws://127.0.0.1:8181/core

websocat-intake:
  rlwrap websocat ws://127.0.0.1:8080/core

build:
  cargo build

audio:
  cargo run --bin audio

message-bus:
  cargo run --bin message_bus

voice:
  cargo run --bin voice
